### ISSUE TITLE
A transactional problem with Multi-Datasource

### ISSUE THREAD

**Issue by SeaEagle** [grails/gorm-hibernate5#12]
Hi, 

When I have a single datasource, the code next work properly
```
    @Transactional
    boolean saveUser(User user) {
        user.setRoleId(1L);
        user.setCode("userCode");
        user.setUserName("userName");
        user.save(flush:true);
        return true;
    }
```
But when I have multi-datasource, the code before can't work properly, and throw an exception :
```
org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:116) ~[grails-datastore-gorm-hibernate5-6.0.3.RELEASE.jar:na]
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:699) ~[hibernate-core-5.0.11.Final.jar:5.0.11.Final]
	at org.grails.orm.hibernate.cfg.GrailsHibernateUtil.setObjectToReadWrite(GrailsHibernateUtil.java:325) ~[grails-datastore-gorm-hibernate5-6.0.3.RELEASE.jar:na]
	at org.grails.orm.hibernate.cfg.GrailsHibernateUtil$setObjectToReadWrite.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[groovy-2.4.7.jar:2.4.7]
	at org.grails.orm.hibernate.HibernateGormInstanceApi.setObjectToReadWrite(HibernateGormInstanceApi.groovy:133) ~[grails-datastore-gorm-hibernate5-6.0.3.RELEASE.jar:na]
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:136) ~[grails-datastore-gorm-hibernate-core-6.0.3.RELEASE.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:151) ~[grails-datastore-gorm-6.0.3.RELEASE.jar:na]
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$save.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[groovy-2.4.7.jar:2.4.7]
	at com.minstone.industry.app.provider.multidsprovider.domain.User.save(User.groovy) ~[classes/:na]
	at com.minstone.industry.app.provider.multidsprovider.domain.User.save(User.groovy) ~[classes/:na]
	at org.grails.datastore.gorm.GormEntity$save.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.7.jar:2.4.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.7.jar:2.4.7]
	at com.minstone.industry.app.provider.multidsprovider.service.UserService.saveUser(UserService.groovy:29) ~[classes/:na]
        ......
```
And I have to change the code :
```
    boolean saveUser(User user) {
        User.withTransaction{
            user.setRoleId(1L);
            user.setCode("userCode");
            user.setUserName("userName");
            user.save(flush:true);
        }
        return true;
    }
```
Do you have any idea to solve this problem ?

**Comment by graemerocher** [comment]
You have to auto wire the correct transactionManager for `@Transactional` to work:

```groovy
@Autowired @Qualifier('transactionManager_foo') PlatformTransactionManager transactionManager
```

Where `foo` is the name of your datasource

**Comment by SeaEagle** [comment]
I followed your tips but failed. The exception as follow :
```
UserService required a bean of type 'org.springframework.transaction.PlatformTransactionManager' that could not be found.
```
I have two datasources in application.yml :
```
dataSources:
    test1:
        pooled: false
        jmxExport: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        driverClassName: com.mysql.jdbc.Driver
        dbCreate: update
        url: jdbc:mysql://127.0.0.1:3306/test1?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: test1
        password: test1
    test2:
        pooled: false
        jmxExport: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        driverClassName: com.mysql.jdbc.Driver
        dbCreate: update
        url: jdbc:mysql://127.0.0.1:3306/test2?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: test2
        password: test2
```
And I debuged my program to trace the **applicationContext**, but I didn't found two transactionManager beans that one named **transactionManager_test1** and the other one is **transactionManager_test2**.

**Comment by graemerocher** [comment]
The `@Transactional` annotation needs to be made multiple data source aware. Relates to https://github.com/grails/grails-data-mapping/issues/802

**Comment by graemerocher** [comment]
Resolved by https://github.com/grails/grails-data-mapping/commit/70e1c6510daf65e0e2e6f086690cc00ac3958a29
