### ISSUE TITLE
Unable to interpolate a variable containing some partial hql inside an hql GString

### ISSUE THREAD

**Issue by gabivis** [grails/gorm-hibernate5#120]
grailsVersion=3.3.9
gormVersion=6.1.11.RELEASE

Consider this query:
` def additionalCondition="where a.name='cow'"`
   `def sql = """select count(a.name) from Animal a ${additionalCondition}"""`
   `def records = Animal.executeQuery(sql, [:], [fetchSize: 1000])`

Exception is thrown:

org.springframework.orm.hibernate5.HibernateQueryException: unexpected token: : near line 1, column 74 [select count(a.name) from com.animals.Animal a :p0]; nested exception is org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: : near line 1, column 74 [select count(a.name) from com.animals.Animal a :p0]
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:253)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:724)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:303)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:243)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:117)
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.executeQuery(AbstractHibernateGormStaticApi.groovy:570)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.executeQuery(GormEntity.groovy:1070)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$executeQuery$6.call(Unknown Source)

Note that it works fine if I just use basic String concatenation:
`def sql = """select count(a.name) from Animal a """ + additionalCondition`

Is this a known issue?

Thanks, Gabi

**Comment by graemerocher** [comment]
This is not a bug and is GORM's SQL/HQL injection attack escaping the query to ensure a security vulnerability is not introduced

**Comment by gabivis** [comment]
I am in the process of upgrading to grails 3 from grails 2, where this kind of syntax worked fine. Anyway, you answer makes sense, thanks for the quick reply.

**Comment by mainpal1** [comment]
> records

Probably you should try to make it a String using `sql.toString()`
