### ISSUE TITLE
7.0.0 - list(sort: "id") - ERROR: function upper(bigint) does not exist

### ISSUE THREAD

**Issue by zyro23** [grails/gorm-hibernate5#134]
looks like after the jpa2 api compat migration, a `MyDomain.list(sort: "foo")` call defaults to case-insensitive sorting. however, when applied to numeric fields - `id`, for example - i get an exception like this:
```
2019-04-21 12:20:00.636  WARN 7072 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42883
2019-04-21 12:20:00.636 ERROR 7072 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: function upper(bigint) does not exist
  No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 445
2019-04-21 12:20:00.642 ERROR 7072 --- [nio-8080-exec-4] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet] with root cause

org.postgresql.util.PSQLException: ERROR: function upper(bigint) does not exist
  No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 445
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy193.executeQuery(Unknown Source)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2167)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1930)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1892)
	at org.hibernate.loader.Loader.doQuery(Loader.java:937)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
	at org.hibernate.loader.Loader.doList(Loader.java:2689)
	at org.hibernate.loader.Loader.doList(Loader.java:2672)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
	at org.hibernate.loader.Loader.list(Loader.java:2501)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:220)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1507)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1537)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1505)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.list(CriteriaQueryTypeQueryAdapter.java:94)
	at org.grails.orm.hibernate.query.HibernateHqlQuery.executeQuery(HibernateHqlQuery.java:47)
	at org.grails.datastore.mapping.query.Query.doList(Query.java:589)
	at org.grails.datastore.mapping.query.Query.list(Query.java:568)
	at org.grails.orm.hibernate.HibernateGormStaticApi$_list_closure1.doCall(HibernateGormStaticApi.groovy:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:122)
	at com.sun.proxy.$Proxy192.doInHibernate(Unknown Source)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:297)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:241)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:120)
	at org.grails.orm.hibernate.HibernateGormStaticApi.list(HibernateGormStaticApi.groovy:78)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.list(GormEntity.groovy:673)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$list$1.call(Unknown Source)
	at foo.Bar.list(Bar.groovy)
	at foo.Bar$list.call(Unknown Source)
	at foo.BarService.$tt__list(BarService.groovy:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
```
i suspect something along the lines of https://github.com/grails/gorm-hibernate5/commit/3ac60b2d4aa86edd2acabeea8c90dcc46977442c#diff-3aa080089819992d7ac7a78b2db382baR307

i tried reproducing with a sample app `HibernateSpec` but it seems this issue is db-specific: while postgresql fails with the exception above, h2 happily executes `upper(id)`:
```
2019-04-21 12:46:44.739 DEBUG --- [    Test worker] org.hibernate.SQL                        : create table dummy (id bigint generated by default as identity, version bigint not null, name varchar(255) not null, primary key (id))
2019-04-21 12:46:45.275 DEBUG --- [    Test worker] org.hibernate.SQL                        : select dummy0_.id as id1_0_, dummy0_.version as version2_0_, dummy0_.name as name3_0_ from dummy dummy0_ order by upper(dummy0_.id) asc
```

if i understand it right, the jpa `criteriaBuilder` does not have a built-in `ignoreCase` support.

hibernate criteria `Order` checks the sqlType prior to enforcing case-insensitivity: https://github.com/hibernate/hibernate-orm/blob/5.4.0/hibernate-core/src/main/java/org/hibernate/criterion/Order.java#L120-L122

and `spring-data-jpa` checks if the targeted property is a `String`: https://github.com/spring-projects/spring-data-jpa/blob/2.1.6.RELEASE/src/main/java/org/springframework/data/jpa/repository/query/JpaQueryCreator.java#L335-L367

env.: win x64, grails-4.0.0.RC1, gorm-7.0.0, oracle jdk 8u131

**Comment by Taack** [comment]
FYI, after debugging, the stack shows we pass into
https://github.com/grails/gorm-hibernate5/blob/3ac60b2d4aa86edd2acabeea8c90dcc46977442c/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/query/GrailsHibernateQueryUtils.java#L177

the ignore case argument is hard-coded to true. 

I do not know how to fix this properly.. We need to retrieve the type of the sorted property, and set ignoreCase accordingly.

**Comment by Taack** [comment]
Patch for passing false to `addOrderPossiblyNested` ignoreCase parameter.

As far as I know, the sort is case sensitive in Grails 3.3.x, so this patch should be acceptable. The other solution is to avoid using upper for something else than String. 

[GrailsHibernateQueryUtils.java.zip](https://github.com/grails/gorm-hibernate5/files/3290643/GrailsHibernateQueryUtils.java.zip)

**Comment by Taack** [comment]
Thanks Jameskleeh, I checked versus 7.0.1.BUILD-SNAPSHOT, there is no more problems on our small CMS. This is great!
