### ISSUE TITLE
Migration from grails 4.0.3 to 4.0.4 causes MissingMethodException with gorm.version 7.0.4.RELEASE

### ISSUE THREAD

**Issue by lkuchars** [grails/gorm-hibernate5#225]
Good morning

I think this commit:
[https://github.com/grails/gorm-hibernate5/commit/5362b197c7c3f4ada4da7143686aa7bda8c2e966#diff-27bcdc54792d4ad8e406bacd6bad7fc2](https://github.com/grails/gorm-hibernate5/commit/5362b197c7c3f4ada4da7143686aa7bda8c2e966#diff-27bcdc54792d4ad8e406bacd6bad7fc2)

Causes grails 4.0.4 (java 11) app fail to start up. Problem is that BeanBuilder do not return anything to iterate over. BeanBuilder implementation must have changed in grails 4.0.4 So generaly the code from commit I mentioned tries to iterate over collection with only one argument. Wchich is BeanBuilder instance

```
`groovy.lang.MissingMethodException: No signature of method: grails.orm.bootstrap.HibernateDatastoreSpringInitializer$_getBeanDefinitions_closure1$_closure3.doCall() is applicable for argument types: (grails.spring.BeanBuilder) values: [grails.spring.BeanBuilder@1072f30e]
Possible solutions: doCall(java.lang.Object, java.lang.Object), findAll(), findAll(), isCase(java.lang.Object), isCase(java.lang.Object)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:255)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2124)
	at org.codehaus.groovy.runtime.dgm$183.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:223)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at grails.orm.bootstrap.HibernateDatastoreSpringInitializer$_getBeanDefinitions_closure1.doCall(HibernateDatastoreSpringInitializer.groovy:163)
	at grails.orm.bootstrap.HibernateDatastoreSpringInitializer$_getBeanDefinitions_closure1.doCall(HibernateDatastoreSpringInitializer.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at grails.plugin.hibernate.HibernateGrailsPlugin$_doWithSpring_closure1.doCall(HibernateGrailsPlugin.groovy:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:399)
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
	at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
	at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:543)
	at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:166)
	at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:171)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:485)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:472)
	at backoffice.Application.main(Application.groovy:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)`

```

**Comment by puneetbehl** [comment]
It will be helpful if you could share a sample application.

**Comment by puneetbehl** [comment]
Also, it seems related to GORM for MongoDB because of the class `grails.mongodb.bootstrap.MongoDbDataStoreSpringInitializer`.

**Comment by lkuchars** [comment]
Sorry yes, MongoDbDataStoreSpringInitializer has exactly the same section of code in initializer which causes the problem. I'll repost proper stacktrace tomorrow. I simply pasted wrong one from clipboard. Also I'll try to come up with minimal app which manifest this.

**Comment by lkuchars** [comment]
I Updated previous stacktrace.

After I started creating hello world project to show this I noticed that what caused this error in my project was following entry in **gradle.properties** file:

```
grailsVersion=4.0.4
gorm.version=7.0.4.RELEASE
```
After bumping gorm.version to 7.0.4.RELEASE all started working. I guess this might be problem for someone who is upgrading from grails 4.0.3 -> 4.0.4. 

I checked that even fresh helloWorld project created with Grails 4.0.4 does not work with gorm.version 7.0.4.RELEASE

Anyway, I'm sorry I wasted your time and thank you for your work for the community.

**Comment by lkuchars** [comment]
Also changing topic of this so if anyone has this problem has change to google it

**Comment by puneetbehl** [comment]
Please confirm if updating `gorm.version` to `7.0.7.RELEASE` or higher fixes the issue.

**Comment by avaneeshGit** [comment]
I am still getting this error even i have gorm.version= 7.0.4.RELEASE in gradle.properties.

**Comment by puneetbehl** [comment]
Please set the gorm.version to 7.0.7.RELEASE

**Comment by abrahaj** [comment]
There is no 7.0.7.RELEASE on artifactors (!?) https://repo.grails.org/grails/core/org/grails/plugins/hibernate5/

**Comment by puneetbehl** [comment]
@abrahaj Please note that `gorm.version` points to the Grails Datastore Core https://repo.grails.org/grails/core/org/grails/grails-datastore-core/

**Comment by johnnywey** [comment]
Stumbled on this via Google with the same issue and wanted to confirm that bumping to `7.0.8.RELEASE` fixed the issue for me - just in case it isn't clear from the thread.
