### ISSUE TITLE
Startup failed with groovy 3.0.6

### ISSUE THREAD

**Issue by beowulf13th** [grails/gorm-hibernate5#237]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a new project with Groovy 3.0.6

build.gradle:

```
plugins {
    id 'groovy'
    id 'org.springframework.boot' version '2.4.0'
    id "io.spring.dependency-management" version "1.0.10.RELEASE"
}

version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core" }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.codehaus.groovy:groovy:3.0.6'

    compile("org.grails:gorm-hibernate5-spring-boot:7.0.4.RELEASE")
    compile "org.hibernate:hibernate-core"
    compile "org.hibernate:hibernate-ehcache"
    runtime "org.postgresql:postgresql:42.2.5"
}

```

Example.groovy
```
import groovy.util.logging.Slf4j
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

@Slf4j
@SpringBootApplication(exclude = HibernateJpaAutoConfiguration.class)
class Example {
    static void main(String... args) {
        SpringApplication.run(Example, args)
    }
}
```
3. Run from Idea as Spring application

### Expected Behaviour

Run correctly

### Actual Behaviour

Run with exception cause try to access private field in 

`grails-datastore-core-7.0.6.RELEASE-sources.jar!/org/grails/datastore/mapping/reflect/ClassPropertyFetcher.java:421`
for
`org.codehaus.groovy.reflection.CachedField#field`

In groovy 2.5 that field is public, but in 3.0 private.

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** org.grails:grails-datastore-gorm:7.0.6.RELEASE
- **Grails Version (if using Grails):** nope
- **JDK Version:** 15

### stacktrace

```org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateDatastore' defined in class path resource [org/grails/datastore/gorm/boot/autoconfigure/HibernateGormAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.orm.hibernate.HibernateDatastore]: Factory method 'hibernateDatastore' threw exception; nested exception is java.lang.IllegalAccessError: class org.grails.datastore.mapping.reflect.ClassPropertyFetcher tried to access private field org.codehaus.groovy.reflection.CachedField.field (org.grails.datastore.mapping.reflect.ClassPropertyFetcher and org.codehaus.groovy.reflection.CachedField are in unnamed module of loader 'app')
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[spring-context-5.3.1.jar:5.3.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.1.jar:5.3.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
	at com.example.demo.DemoApplication.main(DemoApplication.groovy:12) ~[main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.orm.hibernate.HibernateDatastore]: Factory method 'hibernateDatastore' threw exception; nested exception is java.lang.IllegalAccessError: class org.grails.datastore.mapping.reflect.ClassPropertyFetcher tried to access private field org.codehaus.groovy.reflection.CachedField.field (org.grails.datastore.mapping.reflect.ClassPropertyFetcher and org.codehaus.groovy.reflection.CachedField are in unnamed module of loader 'app')
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.3.1.jar:5.3.1]
	... 20 common frames omitted
Caused by: java.lang.IllegalAccessError: class org.grails.datastore.mapping.reflect.ClassPropertyFetcher tried to access private field org.codehaus.groovy.reflection.CachedField.field (org.grails.datastore.mapping.reflect.ClassPropertyFetcher and org.codehaus.groovy.reflection.CachedField are in unnamed module of loader 'app')
	at org.grails.datastore.mapping.reflect.ClassPropertyFetcher.getDeclaredField(ClassPropertyFetcher.java:421) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.datastore.mapping.model.config.GormMappingConfigurationStrategy.getPersistentProperties(GormMappingConfigurationStrategy.java:177) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.datastore.mapping.model.config.JpaMappingConfigurationStrategy.getPersistentProperties(JpaMappingConfigurationStrategy.java:35) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.datastore.mapping.model.AbstractPersistentEntity.initialize(AbstractPersistentEntity.java:134) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.datastore.mapping.model.AbstractMappingContext.initializePersistentEntity(AbstractMappingContext.java:352) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.datastore.mapping.model.AbstractMappingContext.addPersistentEntities(AbstractMappingContext.java:283) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.orm.hibernate.cfg.HibernateMappingContext.<init>(HibernateMappingContext.java:73) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.buildConfiguration(HibernateConnectionSourceFactory.java:94) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:85) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24) ~[grails-datastore-core-7.0.6.RELEASE.jar:na]
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:212) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:244) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:266) ~[grails-datastore-gorm-hibernate5-7.0.4.RELEASE.jar:na]
	at org.grails.datastore.gorm.boot.autoconfigure.HibernateGormAutoConfiguration.hibernateDatastore(HibernateGormAutoConfiguration.groovy:101) ~[gorm-hibernate5-spring-boot-7.0.4.RELEASE.jar:na]
	at org.grails.datastore.gorm.boot.autoconfigure.HibernateGormAutoConfiguration$$EnhancerBySpringCGLIB$$92246c21.CGLIB$hibernateDatastore$13(<generated>) ~[gorm-hibernate5-spring-boot-7.0.4.RELEASE.jar:na]
	at org.grails.datastore.gorm.boot.autoconfigure.HibernateGormAutoConfiguration$$EnhancerBySpringCGLIB$$92246c21$$FastClassBySpringCGLIB$$b6d82bc5.invoke(<generated>) ~[gorm-hibernate5-spring-boot-7.0.4.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.1.jar:5.3.1]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.1.jar:5.3.1]
	at org.grails.datastore.gorm.boot.autoconfigure.HibernateGormAutoConfiguration$$EnhancerBySpringCGLIB$$92246c21.hibernateDatastore(<generated>) ~[gorm-hibernate5-spring-boot-7.0.4.RELEASE.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.1.jar:5.3.1]
	... 21 common frames omitted

```

### Github link

https://github.com/beowulf13th/grails-groovy3

**Comment by beowulf13th** [comment]
Was fixed in 

https://github.com/grails/grails-data-mapping/commit/9607c1f688aad0e1746071118b6d23b70185efba#diff-14bb55a77624b12b84e69c391b0749f5be1f5afc86d22d8c4e440278659cfb71R421

**Comment by beowulf13th** [comment]
Possible workaround

```
compile("org.grails:grails-datastore-gorm") {
		version {
			strictly '7.1.0.M3'
		}
	}
```

**Comment by puneetbehl** [comment]
Right, GORM 7.0.x does not support Groovy 3. You would need to use 7.1.x for the same. Also, you may want to update to GORM for Hibernate 7.1.0.M2 as well. 

See Release Notes at https://github.com/grails/gorm-hibernate5/releases/tag/v7.1.0.M2
