### ISSUE TITLE
NullPointerException at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindSubClass(GrailsDomainBinder.java:1508)

### ISSUE THREAD

**Issue by maiconandsilva** [grails/gorm-hibernate5#607]
In  `GrailsDomainBinder.bindSubClass` the call to [`getMapping(parent.getMappedClass());` ](https://github.com/grails/gorm-hibernate5/blob/d0187c78efc1fbae7c3fb6785190dbb3af41d5f4/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/GrailsDomainBinder.java#L1483)is returning null. This is due to wrong mappings on the application using gorm-hibernate5. As I'm upgrading Grails to version 5 there are some. This error prevents the developer from knowing the actual origin of the error.

One example is when using id composite with just one column. It worked in previous versions (2.3.*).

```
class Teste implements Serializable {
    String nome

    static mapping = {
        id composite: ['nome']
    }
}
```

Relevant Stacktrace:
```
Caused by: java.lang.NullPointerException: null
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindSubClass(GrailsDomainBinder.java:1508)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindSubClasses(GrailsDomainBinder.java:1467)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.bindRoot(GrailsDomainBinder.java:1410)
	at org.grails.orm.hibernate.cfg.GrailsDomainBinder.contribute(GrailsDomainBinder.java:161)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:292)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:709)
	at org.grails.orm.hibernate.cfg.HibernateMappingContextConfiguration.buildSessionFactory(HibernateMappingContextConfiguration.java:287)
	at org.grails.orm.hibernate.connections.HibernateConnectionSourceFactory.create(HibernateConnectionSourceFactory.java:86)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:39)
	at org.grails.orm.hibernate.connections.AbstractHibernateConnectionSourceFactory.create(AbstractHibernateConnectionSourceFactory.java:23)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
	at org.grails.orm.hibernate.HibernateDatastore.<init>(HibernateDatastore.java:212)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
```

**Comment by daraii** [comment]
@maiconandsilva The problem is related to the Spring Boot Devtools as having it in the project creates a second classloader (the restart classloader) and when the GrailsDomainBinder is going to get the cached mapped class it does not find it since the class it's trying to find and the class in the cache are in different classloaders thus not equal.

As a workaround you can remove the devtools dependency from your project's build.gradle or you can check the https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.devtools "Customizing the Restart Classloader" section and exclude the domain classes. Unfortunately the code won't reload if the excluded classes are changed.

**Comment by maiconandsilva** [comment]
@daraii, Thank you. Removing this dependency solves my problem. I just wanted to read meaningful error messages. Thank you a lot!
