### ISSUE TITLE
how to hot-deploy GORM project in weblogic?

### ISSUE THREAD

**Issue by xp13910818313** [grails/gorm-hibernate5#74]
i have a spring boot project using GORM & groovy, deploy in weblogic 12c (12213).
Weblogic throw frozen class RuntimeException,when we update project (hot-deploy) from weblogic console. How to fix it to support hot-deploy?

`<Error> <Deployer> <BEA-149265> <Failure occurred in the execution of deployment request with ID "5768901220916096" for task "9" on [partition-name: DOMAIN]. Error is: "weblogic.application.ModuleException: java.lang.RuntimeException: org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer: frozen class (cannot edit)"
weblogic.application.ModuleException: java.lang.RuntimeException: org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer: frozen class (cannot edit)
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.RuntimeException: org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer: frozen class (cannot edit)
	at javassist.ClassPool.checkNotFrozen(ClassPool.java:610)
	at javassist.ClassPool.makeClass(ClassPool.java:852)
	at org.grails.orm.hibernate.proxy.ProxyFactorySupport.<clinit>(ProxyFactorySupport.groovy:38)
	at org.grails.orm.hibernate.cfg.GrailsHibernateUtil.buildProxyFactory(GrailsHibernateUtil.java:418)
	at org.grails.orm.hibernate.proxy.GroovyAwarePojoEntityTuplizer.buildProxyFactory(GroovyAwarePojoEntityTuplizer.java:45)`

**Comment by douglasom** [comment]
Why did you close this issue? When deploying a grails 3.3.10 application on weblogic we're having to restart the vms, otherwise we get the following error:

`java.lang.RuntimeException: org.grails.orm.hibernate.cfg.IdentityEnumType: frozen class (cannot edit)`

**Comment by leleFc** [comment]
I have a similar issue on IBM Websphere 8.5.5.13 and Grails 3.3.10

java.lang.RuntimeException: org.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer: frozen class (cannot edit)

I'm using javassist 3.18.2-GA as shared library.
I can't do an hot deploy, but if I stop and restart WAS, my application starts correctly.

**Comment by leleFc** [comment]
In my case this is a WAS class loader problem

**Comment by jesusrodriguezmjp** [comment]
I'm having this exact issue deploying in a WebLogic server. I have to restart the web server, or it doesn't work (Grails 3.3.14, GORM 6.1.12). Is there any fix or workaround?
