### ISSUE TITLE
how to support springboot 3.x ？

### ISSUE THREAD

**Issue by xp13910818313** [grails/gorm-hibernate5#751]
We have created a sample application through https://start.spring.io/,  add Gorm8.0 and one simple domain class:
domain class
```
@Entity
class Book {
    String title
}
```
Springboot 3.1.3 
Gorm 8.0.0
JDK 17.0.8
got these errors:
 ```
java.lang.IllegalStateException: Either class [com.example.Book] is not a domain class or GORM has not been initialized correctly or has already been shutdown. Ensure GORM is loaded and configured correctly before calling any methods on a GORM entity.
	at org.grails.datastore.gorm.GormEnhancer.stateException(GormEnhancer.groovy:467) ~[grails-datastore-gorm-8.0.0.jar:na]
	at org.grails.datastore.gorm.GormEnhancer.findInstanceApi(GormEnhancer.groovy:315) ~[grails-datastore-gorm-8.0.0.jar:na]
```

we changed build.gradle like that ,still got wrong:
```
dependencies {
    implementation("org.grails:gorm-hibernate5-spring-boot:8.0.0"){
        exclude module: "groovy"
    }
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.codehaus.groovy:groovy:3.0.19'
    //implementation 'org.apache.groovy:groovy'
}
```

how to fix it ?

**Comment by puneetbehl** [comment]
Currently, Grails 6.0 does not support Spring Boot 3. We are planning to support it with Grails 7.

**Comment by xp13910818313** [comment]
thanks

**Comment by xp13910818313** [comment]
[
![springboot2 7](https://github.com/grails/gorm-hibernate5/assets/11690092/b24f07e7-57a1-4c0c-bf90-9e472ed547b8)
](url)

**Comment by xp13910818313** [comment]
@puneetbehl , when will release GORM 9.0.X  ?
