### ISSUE TITLE
Spring @Transactional not applied for GORM methods in java

### ISSUE THREAD

**Issue by injecteer** [grails/gorm-hibernate5#816]
In my Spring-Boot app I'm using GORM via:
```
implementation 'org.grails:gorm-hibernate5-spring-boot:8.0.3'
```
All domain classes are annotated with GORM `@Entity` and are initialized with `new HibernateDatastore( cfg, classes )` and work like a charm.

I also created a delegating helper class to call dynamic GORM methods from java:
```
class JavaGORMHelper {
  
  static <T extends GormEntity> void withTransaction( Class<T> clazz, Consumer<TransactionStatus> action ) {
    clazz.withTransaction{ action it }
  }
  
  static <T extends GormEntity> T list( Class<T> clazz ) {
    clazz.list()
  }

  // other 40 methods
}
```

Now I want to call those GORM methods from java service and for that I would use Spring's `@Transactional`:

```
import org.springframework.transaction.annotation.Transactional;

@Service
public class JobService {

  @PostConstruct
  @Transactional(readOnly = true, propagation = Propagation.REQUIRES_NEW)
  public void init() {  
    JavaGORMHelper.list(Job.class).forEach(job -> foo( job ));
  }
}
```

The code is throwing a `No Session found for current thread` exception:
```
[main] 16:23:37.303 ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobController': Unsatisfied dependency expressed through field 'jobService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jobService': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)
	... 20++ common frames omitted
Caused by: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:335)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:284)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:241)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:120)
	... 32++ common frames omitted
Caused by: org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:112)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:508)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:333)
	... 56 common frames omitted
```

I tried exposing `transactionManager` and `sessionFactory` from `HibernateDatastore` as spring beans with no success.

If I wrap the method call into `JavaGORMHelper.withTransaction(Job.class, tx -> {..});` it works fine.

Also it works fine if I convert the java service to groovy and use `@grails.gorm.transactions.Transactional`.

See also the [SO-Question](https://stackoverflow.com/questions/77861090/spring-transactional-not-applied-for-gorm-methods-in-java/77861184)

**Comment by injecteer** [comment]
further details in [my answer](https://stackoverflow.com/a/78000324/1682820)
